### ISSUE TITLE
ImportError: No module named pyngrok

### ISSUE THREAD

**Issue by 9MadDemon9** [gitphis/gitphis#2]
ImportError: No module named pyngrok 
![IMG_20210928_132354](https://user-images.githubusercontent.com/53664145/135069981-66ae2db3-945e-4f2b-a2f7-4b3c4f867814.jpg)
Got an error like this while running the script I reinstalled pyngrok but it's says:-

bash-5.1$ pip install pyngrok                                                                                         Requirement already satisfied: pyngrok in /data/data/com.termux/files/usr/lib/python3.9/site-packages (5.1.0)
Requirement already satisfied: PyYAML in /data/data/com.termux/files/usr/lib/python3.9/site-packages (from pyngrok) (5.4.1)

**Comment by gitphis** [comment]
Pip install pyngrok
